[package]
name = "tfhe-vote-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
bincode = { version = "2.0.1", features = ["serde"] }
serde   = { version = "1.0", features = ["derive"] }
tfhe = { version = "~1.3.2", features = ["integer"] }
